### ISSUE TITLE
CLI for registering the clients

### ISSUE THREAD

**Issue by eugulixes** [tolstoyevsky/hubot-huntflow-reloaded#33]
We need to have a command-line tool which will help us to register the clients. The bot will be one of the clients. The bot must be authenticated because it will be sending requests for removing some events from the database and listing the candidates. However, do not implement authentication logic closing the issue.

**Comment by ya7on** [comment]
Checklist:
- [ ] Model
- [ ] Arguments parsing
- [ ] Password generating
- [ ] Database record saving
- [ ] Email sending
